[package]
name = "lomb"
version = "0.2.0"
authors = ["Jubin Lirawi <jubin@lirawi.de>"]
edition = "2021"
rust-version = "1.67.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"